name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.0

      - name: Use Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: build library
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: build website
        run: |
          go get bitbucket.org/tmedwards/tweego
          export PATH=$PATH:$(go env GOPATH)/bin
          npm run build-site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_PAT }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
